# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo requirements.txt al contenedor
COPY requirements.txt /app/

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código fuente de la aplicación al contenedor
COPY . /app

# Expone el puerto 5000 para que la aplicación sea accesible
EXPOSE 5000

# Define el comando para ejecutar la aplicación (en este caso, con Flask)
CMD ["python", "app.py"]
